name: Deploy to AWS
on: 
  push:
    branches:
      - master
jobs:
  Deploy-to-AWS:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.19'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy
        run: make deploy