name: Deploy to AWS
on: 
  push:
    branches:
      - main
jobs:
  Deploy-to-AWS:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.19'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        working-directory: hello-world
        run: |
          go get .
          GOOS=linux GOARCH=amd64 go build -o hello-world
      - name: Deploy
        run: |
          terraform init
          terraform apply -auto-approve
          echo "$$(terraform output -raw base_url)"